runtime: nodejs
env: flex

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|map))$
  static_files: build/\1
  upload: build/.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|map)$
  expiration: "7d"
  secure: always

- url: /.*
  static_files: build/index.html
  upload: build/index.html
  expiration: "0s"
  secure: always

skip_files:
- node_modules/
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.json$
- ^(.*/)?.*\.yaml$
- ^(.*/)?.*\.yml$
- ^(.*/)?.*\.lock$
- ^(.*/)?.*\.dockerignore$
- ^(.*/)?.*Dockerfile$
